### ISSUE TITLE
AttributeError on some words

### ISSUE THREAD

**Issue by ookimi** [Suyash458/WiktionaryParser#19]
Trying to obtain a parser object for the word "patronise" (entry exists and looks like the others):

Traceback (most recent call last):
  File "/path/path/path/noise.py", line 562, in wikidata
    return WiktionaryParser().fetch(word)
  File "/home/user/py36/lib/python3.6/site-packages/wiktionaryparser/WikiParse.py", line 308, in fetch
    return self.get_word_data(language.lower())
  File "/home/user/py36/lib/python3.6/site-packages/wiktionaryparser/WikiParse.py", line 117, in get_word_data
    'definitions': self.parse_definitions(word_contents),
  File "/home/user/py36/lib/python3.6/site-packages/wiktionaryparser/WikiParse.py", line 168, in parse_definitions
    while table.name != 'ol':
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by Suyash458** [comment]
Fixed in 5952be49ecc6eb13aed74b5c06f0e56728c631b0

**Comment by aghasemi** [comment]
Hi,
This still happens to me: https://github.com/Suyash458/WiktionaryParser/issues/53
